# Generated by Django 3.0.2 on 2020-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency_pair', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exchange_rate', models.FloatField()),
            ],
        ),
    ]
